name: learn-github-actions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test